name: Taxonomy build & validation
on:
  workflow_dispatch:
  push:

env:
  TAX_NAME: rj_taxonomy_2024

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build taxonomy-package
    steps:
      - uses: actions/checkout@v4
      - run: mkdir -p build

      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r build/$TAX_NAME.zip . -i $TAX_NAME
      # - run: './script/worker.sh '

      - uses: actions/upload-artifact@master
        with:
          name: $TAX_NAME.zip
          path: build/$TAX_NAME.zip


  test:
    runs-on: ubuntu-latest
    name: Test taxonomy-package
    needs: build
    steps:
      - uses: robinraju/release-downloader@v1.9
        with:
          repository: arelle/arelle
          latest: true
          tarBall: true
          out-file-path: arelle
          extract: true
      - uses: actions/download-artifact@v4
        with:
          name: TAX_NAME.zip
          path: taxonomies
