name: Taxonomy build & validation
on:
  workflow_dispatch:
  push:

env:
  TAX_NAME: rj_taxonomy_2024

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    name: Build en Test taxonomy-package
    steps:
      - uses: actions/checkout@v4

      - run: mkdir -p build
      - uses: montudor/action-zip@v1
        with:
          args: zip -r build/${{ env.TAX_NAME }}  ./${{ env.TAX_NAME }}

      - uses: actions/upload-artifact@master
        with:
          name: ${{ env.TAX_NAME }}.zip
          path: build/${{ env.TAX_NAME }}.zip

      - name: Install Arelle
        run: |
          pip install arelle-release

      # We willen de entrypoints kennen, dus manifest lezen
      - id: eplist
        run: |
          EP_LIST=`python scripts/find-entrypoints.py ${{ env.TAX_NAME }}` 
          echo ep_list=$EP_LIST >> $GITHUB_ENV
      - run: |
          echo ${{ env.ep_list }}
      - id: taxtest
        run: |  # dit kan niet in een single taxo met dependencies: --file "${{ env.ep_list }}"
          arelleCmdLine --packages build/${{ env.TAX_NAME }}.zip  --validate

      #- run: |
      #    arelleCmdLine  --file "$env:ENTRYPOINT_LIST" --validate --logLevel=warning --logFile=arelle-taxo.log
