name: Taxonomy build & validation
on:
  workflow_dispatch:
  push:

env:
  TAX_NAME: rj_taxonomy_2024

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build taxonomy-package
    steps:
      - uses: actions/checkout@v3
      - run: mkdir -p build

      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r build/$TAX_NAME.zip $TAX_NAME
      # - run: './script/worker.sh '

      - uses: actions/upload-artifact@master
        with:
          name: $TAX_NAME.zip
          path: build/$TAX_NAME.zip


